# This file has been generated by niv - dependency manager for Nix projects
# For use with legacy nix-shell (non-flakes)

let
  # Simplified sources for nixpkgs pinning
  nixpkgs = builtins.fetchTarball {
    # nixos-24.05 channel
    url = "https://github.com/NixOS/nixpkgs/archive/refs/tags/24.05.tar.gz";
    sha256 = "1lr1h35prqkd1mkmzriwlpvxcb34kmhc9dnr48gkm8hh089hifmx";
  };
in
{
  nixpkgs = nixpkgs;
}
